<a href="https://colab.research.google.com/github/maharshi112/looking-forward/blob/master/Day_1_Numpy_1_Class_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <mark>Data Analysis and Visualization (DAV)</mark>

This entire DAV section of the course is divided into three parts:
1. DAV-1 - Python libraries - Time to complete - 1 month and 1 week
2. DAV-2 - Probability and Statistics
3. DAV-3 - Hypothesis Testing

DAV-2 and 3 in total will take 2 to 2.5 months to complete.

# <mark>What is Numpy</mark>

**NumPy, which stands for "Numerical Python," is a fundamental Python library for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays.**

**NumPy is a free and open-source library, and is available for download from the NumPy website.**

**Here are some of the primary use cases for NumPy:**

* **<u>Multi-dimensional Array Operations:</u>** NumPy's primary data structure is the ndarray (n-dimensional array), which allows you to work with arrays of data efficiently. These arrays can have any number of dimensions and are used for tasks like representing data, images, and more.

* **<u>Mathematical and Statistical Operations:</u>** NumPy provides a rich set of mathematical and statistical functions, making it suitable for tasks involving linear algebra, calculus, statistics, and more. You can perform operations like addition, subtraction, multiplication, and division on arrays, as well as advanced operations like matrix multiplication, eigenvalue decomposition, and singular value decomposition.

* **<u>Data Manipulation and Analysis:</u>** NumPy is often used in conjunction with libraries like pandas for data manipulation and analysis. It allows you to load, transform, and manipulate data efficiently, making it a foundational tool for data scientists and analysts.

* **<u>Machine Learning and Data Science:</u>** NumPy serves as a fundamental building block for many machine learning libraries and frameworks, including scikit-learn and TensorFlow. It's used for creating and manipulating data arrays that are fed into machine learning algorithms.

* **<u>Plotting and Data Visualization:</u>** While NumPy itself is not designed for data visualization, it is often used in combination with libraries like Matplotlib and Seaborn to create plots, charts, and visualizations from numerical data.

* **<u>Random Number Generation:</u>** NumPy includes a random number generation module that is useful for tasks like simulations and statistical analysis.

**Overall, NumPy is a fundamental tool in the Python ecosystem, and its versatility and efficiency make it indispensable for a wide range of applications, particularly in scientific and numerical computing.**

**NumPy is widely used in data science, machine learning, scientific research, and many other fields where numerical and mathematical operations on large datasets are required.**

In [ ]:
a = [1, 4.5, "string", True, 7890234567874345678765, "this is a massive string with a tonne of characters"]

In [ ]:
a

[1,
 4.5,
 'string',
 True,
 7890234567874345678765,
 'this is a massive string with a tonne of characters']

# <mark>Python lists are heterogenous</mark>

* We have learnt about python lists. Lets talk about a very curious aspect of python lists.
<u>We have seen that python lists can be heterogenous</u>, which means it can store various datatypes as its elements at the same  time as shown above.

* But heterogeneity actually creates a problem. Now, in the example below, can we say that int "1" and the string that we have
at the end will require different space in memory? <u>They will require different amount of memory to be stored in the RAM.</u>

* Now because they are not same amount of data, they require different amounts of memory for their storage, the
**storage actually cannot be together. They cannot be stored in boxes in continuous manner in RAM.**

* Boxes in memory have same size-- for example, each box can store 4 bytes of data. So, if data is equal to or small in size
than 4 bytes, we can keep on storing data in contiguous or continuous manner in boxes.

* **Because python is a dynamic programming language which supports heterogeneity, which means when we create lists, we dont tell python what type of data we are going to store in it, means data can be variable in size and HENCE we dont or cant predict the size of data in python lists.**

* Think of RAM as a hugh blob of memory. And now somewhere in RAM, "1" will be stored somewhere, "4.5" will be stored
somewhere completely else, "string" will be completely at a different place, same goes with boolean and large int.

* **What happens internally is, when we create a python list, python stores the memory addresses of the locations where the list elements are stored.**

* Lets suppose we are makng tea and we go to a friend's house and make tea. Now in case 1, all the ingridients to make tea are very well organised and stored in one drawer next to each other. But in case 2, all of these ingridients are present in a list where you have been given the locations of those ingridients, where you will find them. But you have to go that address, fetch that ingridient and use it and repeat the process.

* In which of the two cases, will we be able to make tea faster? Obviosly 1st case will be faster.

* **So, whenever we have heterogeneity, it makes something slow. It comes at a cost. Its like a superpower but it makes lists bulky. Slow because they allow you for dynamic input of type of elements and customization.**

# <mark>Numpy only handles homogenous data</mark>

* **Whenever we will be working with numpy, we will always be working with homogenous data, which means numpy lists will only contain ints or it will only contain floats  or it will only contain strings. So, thats why numpy lists are called numpy arrays.**

* These numpy arrays are similar to arrays in other programming languages like c++, where arrays are having elements of the
same data type.

* **Numpy arrays only store homogeneous data. Homogeneous data will be consistent in size, if its consistent in size, it can be stored in contiguous or continuous memory locations. Numpy arrays could actually be faster than python lists. WE WILL PROVE THIS.**

* We have heard that Java, C, C++ are fast programming languages than python. Why is python slow?
Because, we have discussed this in the first lecure of python, that **PYTHON IS BUILT AS AN ABSTRACTION ON TOP OF C. Python ultimately gets converted into C code, which then gets converted into machine code. "C is where the python compiler sits."**

* Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

* If we run python in cmd prompt, you will see Clang 13.0.0. and that tells you that python interpretor is built in C.
**So, what happens is that python code gets converted into C code, which then gets complied into machine code.
So, since there is an added step on top of C program, ultimately by nature its bound to get slow.**

* **But numpy, even though it works with python, internally directly uses C, so numpy is not an abstraction on top of C.
Numpy is also an abstraction on top of C, but it utilizes a lot of properties of C, which python does not. So, although python introduced heterogeneity, numpy doesnt introduce it. Numpy is homogenous. Numpy uses a lot of features directly from C and that is why numpy is faster than a lot of core python concepts. Since, numpy is directly compatible with C and C is a homogenous language, numpy arrays are faster than python lists.**

* Numpy and python work in conjunction with each other to get their code converted to C and then to machine language.
Numpy's compatibility with is actually better than python. At the same time all of the python concepts like indexing etc will also work with numpy.

* **As a data scientist who has to work with millions and millions of data, numpy becomes very obvious choice. And, numpy
is omnipresent in all DA/DS roles without fail its gonna come.**

* So, numpy array is built on top of C and is more compatible with C and also takes a lot of features of both C and python, but since its homogenous, its lot faster than python lists. Numpy library is built on top of C not on python.

** Here "a" is a heterogenous python list. **

** Importing a module. **

In [ ]:
import math as m

** Now all the module's methods are available to use with the help of the alias and dot operator. **

In [ ]:
m.log(10)

2.302585092994046

### <mark>Using NumPy</mark>

** Once you've installed NumPy you can import it as a library. **

In [ ]:
import numpy as np

** Lets create a normal python list a. **

In [ ]:
a = [1,2,3,4,5]

** We are creating a python list "res", using list comprehension to create squares of elements of a. **

In [ ]:
res = [i ** 2 for i in a]

In [ ]:
res

[1, 4, 9, 16, 25]

### <mark>Creating NumPy Arrays from a Python List</mark>

**We can create a numpy array using a method called <code style="background:yellow;color:black">array()</code>, which is defined for array object in numpy. We pass a python list or nested lists in array() method as parameters to create nD numpy array.**

**We can also create a nD array by directly converting a python list or nested list. Following is an example of creating a numpy array b using <mark>"typecasting"</mark> i.e. typecast a python list into a numpy array.**

In [ ]:
b = np.array(a)

In [ ]:
b

array([1, 2, 3, 4, 5])

** Type of "b" is a n dimensional array. Here, "b" is 1D array. **

In [ ]:
type(b)

numpy.ndarray

** As we can see "a" is a normal python list. **

In [ ]:
type(a)

list

### <mark>Numpy arrays support element wise operations</mark>

In [ ]:
b

array([1, 2, 3, 4, 5])

** This operation of element wise operation wont work with python lists. **

In [ ]:
a ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

** Same operation of squares of elements but using numpy. **

In [ ]:
b ** 2

array([ 1,  4,  9, 16, 25])

### <mark>New function to check execution time of a particular operation</mark>

** We are checking through this function, how much computation time it takes in case of a python list. **

In [ ]:
%timeit [i ** 2 for i in a]

811 ns ± 40.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


** Python list's processing times in case of cubes, are in micro seconds. **

In [ ]:
%timeit [i ** 3 for i in range(100000)]

17.9 ms ± 715 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
l = np.array(range(100000))

** We are checking through this function, how much computation time it takes in case of a numpy array called l. **

**Hence proved that <mark>numpy arrays are 1000 times faster than python lists</mark> because when we compare numpy array's processing times in case of cubes, they are in micro seconds whereas python list's processing times are in milliseconds.**

In [ ]:
%timeit l ** 3

304 µs ± 5.25 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### <mark>Why is numpy so fast?</mark>

Numpy is often significantly faster than pure python when it comes to numerical and scientific computing tasks. This is because numpy is designed for efficient array operations and mathematical computations, and it's implemented in low-level languages like C, which can perform operations much faster than python, which is an interpreted, high-level language.

- **Homogeneous datatype-** Homogeneity allows NumPy to use contiguous blocks of memory and perform operations more efficiently.
- **Parallelism-** Numpy divides tasks in parallel processes, meaning numpy can take advantage of multi-core processors and parallelism, which speeds up computations for large datasets.
- **Optimized C Code-** Numpy functions are directly implemented in C. Many of the core functions in NumPy are implemented in C, which is a low-level language that can execute code much faster than Python. This means that many NumPy operations are faster than their equivalent pure Python implementations.
- **Vectorization-** Numpy supports vectorized operations, which means it can operate on entire arrays without the need for explicit Python loops. This allows for highly optimized, low-level operations on data, leading to improved performance.

In [ ]:
a = np.array(range(10000))

**The <mark>.ndim attribute</mark> in NumPy is used to determine the number of dimensions or axes in a NumPy array. It stands for "number of dimensions." This attribute is particularly useful when you want to understand the dimensionality of an array, which is crucial for many operations and manipulations.**

The .ndim attribute provides a simple and convenient way to check the dimensionality of an array, which is useful when you want to ensure that you are working with data of the correct shape or when you need to perform operations specific to the number of dimensions in your array.

In [ ]:
a.ndim

1

**The <mark>.shape attribute</mark> in NumPy is not actually a method; it's an attribute of a NumPy array. It provides information about the dimensions of the array. Specifically, it returns a tuple that represents the size of each dimension in the array.**

For a 1-dimensional array, the shape attribute will be a tuple with a single element indicating the number of elements along that dimension. For multi-dimensional arrays, the shape attribute will be a tuple with multiple elements, each element corresponding to the size of a particular dimension.

In [ ]:
a.shape

(10000,)

**Lets create a 2D numpy array b using array() method introduced in the beginning.**

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b.ndim

2

In [ ]:
b.shape

(4, 3)

** Lets create a 1D numpy array a. **

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(8,)

** Visualization of 3D array is in the notes. Refer that. In fact refer notes always. **

We have already learnt about range() method in python.

**A similar method also exists in numpy called <mark>arange()</mark>, by which we can create a 1D array or a sequence of elements in numpy.**

Range in python generates a sequence, we can have a start point, end point and a step size; Similarly arange() can also have starting point, end point and step size. Starting point is included, ending point isnt included just like range().

There is one very important thing about this, that its spelled as arange() with a single "r" not double "rr".
Many people make this mistake, so be careful.

**<mark>np.arange() and np.array(range())</mark> are two ways to create 1D Numpy arrays with regularly spaced values, but they differ in terms of usage and flexibility.**

* **np.arange()**: np.arange() is a function provided by numpy to create a 1D array of evenly spaced values within a specified range. We specify the start, stop, and step size as arguments. For example: np.arange(start, stop, step). It returns an array with values from start to (but not including) stop, incrementing by step.

* **np.array(range())**: In this approach, we first create a python range object using the built-in range() method and then convert it to a numpy array using np.array(). We typically specify the start, stop, and step size using range() and then convert it into an array.

**In practice, np.arange() is more convenient and commonly used because it directly generates a numpy array with the specified values, whereas np.array(range()) involves an extra step of creating a python range object and then converting it into a numpy array. However, both methods ultimately achieve the same result in terms of creating 1D arrays with evenly spaced values.**

** Format of "arange()" is - np.arange(start, end, step_size) **

** It works exactly like range(), default step size is 1 same as range(), ending value isnt included just like range(). **

** Lets create a 1D numpy array a1. **

In [ ]:
a1 = np.arange(1, 5)

In [ ]:
a1

array([1, 2, 3, 4])

** Different step size. **

In [ ]:
a2 = np.arange(1, 5, 2)

** Note that ending element i.e "5" isnt included. **

In [ ]:
a2

array([1, 3])

One added functionality we get in "arange()" but will not work in case of lists or python range() function is that it can also work with <mark>floating point step sizes or jump values.</mark>

This is one added advantage that we get on top of python range() function.

In [ ]:
a3 = np.arange(1, 5, 0.5)

Here, step size or jump is of "0.5".

One imp thing to note here is that since numpy arrays are homogenous, it cant have int and float together, so in final result array <mark>all integers got automatically converted to floating point values to maintain homogeneity.</mark>

In [ ]:
a3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### <mark>Indexing-</mark>

**All sorts of indexing - positive, negetive works on numpy arrays, we can fetch first element like this-**

In [ ]:
a3[0]

1.0

** Last element can be fetched like this- **

In [ ]:
a3[-1]

4.5

### <mark>Slicing-</mark>

**Slicing also works similarly in numpy.**

In [ ]:
a3[2:5]

array([2. , 2.5, 3. ])

Like we saw, all the integer values got converted automatically to floating point values in order for it to maintain homogeneity; so if we have a list of int and float, numpy will automatically convert them all into floating
point values, like in this example below:

In [ ]:
a = [1, 2, 3, 4, 5.6]

In [ ]:
a = np.array(a)

In [ ]:
a

array([1. , 2. , 3. , 4. , 5.6])

But what if, we have something like this in the example below.

We have a string and integers, what will numpy do now? -- <mark>It converts them all to strings.</mark> Everything is convertible to strings. Even numbers can be strings. Homogeneity is still maintained. And it also tells us the datatype in the rightmost area of the output.

U21 is basically a unicode representation, its a mapping similar to ASCII. It basically tells you that these are strings.

In [ ]:
b = np.array(["bipin kalra", 1, 2, 3, 4, 5])

In [ ]:
b

array(['bipin kalra', '1', '2', '3', '4', '5'], dtype='<U11')

Like we saw, all the integer values got converted automatically to floating point values in order for it to maintain homogeneity; so if we have a list of int and float, numpy will automatically convert them all into floating
point values.

But what if we dont want it to do automatically, that is, we dont want numpy to convert ints to floats forcibly, automatically.
For eg, if we provide an array like this in example - c = np.array([1,2,3,4.5]), we dont want the default output - array([1. , 2. , 3. , 4.5]).

**When typecasting happens automaticaly, we call this <mark>INTRINSIC TYPECASTING,</mark> but when typecasting happens manually based on user preference, we call this <mark>EXTRINSIC TYPECASTING.</mark>**

Lets see this example below of extrinsic typecasting- here we are specifying, in the rightmost area the datatype of float.

In [ ]:
d = np.array([1,2,3,4], dtype = "float")

In [ ]:
d

array([1., 2., 3., 4.])

If we provide a heterogenous list to a numpy array, all the different datatypes can be converted to one common consistent datatype, and numpy will do that. It will automatically do that type conversion.

But if we want to do it ourself, lets suppose we are providing a bunch of ints and we want to convert them to floats manually,
we can also specify the datatype that this numpy array is going to have at the time of creation of that array,
by specifying dtype = "float" or for string dtype = "U21".

**A problem or shortcoming of this, that when we provide the user the capability to change, user can do something like this
in the example below. Floats can be converted to strings. <mark>CAN STRINGS BE CONVERTED TO FLOATS? NO THATS NO POSSIBLE. THATS WHERE ERROR OCCURS.</mark> Its nonsensical to a certain degree. And thats why numpy does not allow that.**

While you have a lot of manual conversion capability avaliable, some of it cant be used.

In [ ]:
e = np.array(["This", "is", "absurd!"], dtype = "float")

ValueError: could not convert string to float: 'This'

### <mark>FANCY INDEXING- indexing that is unique to numpy- also called MASKING</mark>

Fancy indexing, often referred to as "masking" in NumPy, is a technique that involves selecting elements from an array based on a set of Boolean conditions (masks) or a list of indices. It allows you to create new arrays or extract specific elements from an existing array by applying conditions or specifying positions. Fancy indexing is a powerful feature in NumPy that provides flexibility in data selection and manipulation.

In [ ]:
m1 = np.array(range(1,11))

In [ ]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

What is the output of this code below? It will return another numpy array which will contain element wise responses. Basically it returns element wise result as a numpy array. Numpy supports element wise operation we know that.

In [ ]:
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

We will learn three different concepts, and we will combine all to create something very powerful.

1. **<u>First concept</u> is that element wise operations are possible, as shown above.**

2. **<u>Second concept</u>- Usually in python, when we have a list like this - a = [1,2,3,4,5] , we cant get different indexes's elements like this - a[1,2,4]. It will throw an error, its not possible in python; selective picking of indexes at the same time. But <u>selective indexing</u> is possible in numpy arrays, as shown below.**

3. **<u>Third concept</u>- Combine the above two types and make a special type of indexing called fancy indexing. Such as - m1[m1 % 2 == 0] -> output -> This will give all the even elements - array([ 2,  4,  6,  8, 10]). WHat happens in details working is explained below.**

In [ ]:
a = [1,2,3,4,5]

** Fetching elements at multiple indexes at the same time is not possible in lists. **

In [ ]:
a[1,2,4]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

**Fetching elements at multiple indexes at the same time is possible in numpy.**

In [ ]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

** You have to provide two sets of square brackets; random order of indexes works too. **

In [ ]:
m1[[1,5,3,4]]

array([2, 6, 4, 5])

In [ ]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m1[m1 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [ ]:
m1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

### BREAKDOWN

- First it will generate result of this - m1 % 2 == 0 -> output of which is an array --> [False, True, False, True, False, True, False, True, False, True]

- And then it will superimpose this on top of this array - [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]. And basically, put them together.

- It will work like this - If the corresponding value to "1" is "false", then it will not keep it and vice versa. And hence we get the final result.

So, this is sort of indexing by using filters or its like a filtering of data because we are filtering data on the basis
of a condition. Only values that correspond to "true" are filtered.

<mark>**Everything in python is an object.**</mark>

When you run the following code, error says it has an inhomogenous shape, which means that when you are working with numpy arrays, you only work with numpy matrices, and you dont work with a data which is not a matrix.

<mark>NumPy arrays are designed to represent multi-dimensional arrays where each dimension (or axis) must have consistent lengths.</mark>

**In terminology, 1D numpy array is called a VECTOR, 2D numpy array is called a MATRIX and 3D numpy array is called 3D numpy array and so on.**

**So, we dont create a 2D numpy array, we create 2D numpy matrix.**

In [ ]:
np.array([[1],[2,3],[4,5,6],[7,8,9,10]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

<hr style="border:2px solid gray">

1. Wherever possible, in numpy lectures, we will discuss very very small case studies or discussions, where we will utilize
whatever we have learnt in the current lecture. In some lectures, we will have it. So, today's case study is about NPS.

2. <mark>**NPS is Net Promoter Score.</mark> Many companies are using NPS as a very important metric to understand how customers are perceiving our product, what is their experience with our product.**

3. In NPS, what we usually get is a rating from 0 to 10. So how likely are you to recommend this product or company to your
friends or colleagues. You are asked to rate on a basis of 0 to 10.

4. Anybody in a range of 0 to 6 is called a **detractor**, that is, this is somebody who might not recommend our product to
somebody else. Anybody in range of 7,8 is called **neutral**, that is, does not like does not hate it but may not recommend.
Anybody in range of 9,10 is basically a **promoter**, that is, somebody who is happy with the product and will recommend
the product to other people and these are the kind of people we need.

5. How we calculate NPS? We calculate NPS by saying **NPS = % promoters - % detrators**. So, fo eg, in 1000 people, how much percentage of people are promoters and how much percentage of people are detractors.

6. **Usually in companies, getting a NPS of > 70 is considered to be amazing. And interestingly NPS IS USED BY MAJORITY OF
FORTUNE 500 COMPANIES. Scaler also uses it. So, if you go in a company to work as a DA, you might work on NPS.**

## <mark>NPS CASE STUDY</mark>

**The "gdown" tool is a command-line utility and Python library for downloading files from Google Drive using their unique file IDs. It's a convenient way to download files from Google Drive without requiring a Google Drive share link. You can use "gdown" to fetch files directly by specifying the file's ID in the URL.**

You need to install the "gdown" library if you haven't already by using pip

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: C:\Users\LENOVO\Desktop\New folder\Module 5- Python Libraries\My Practice\Class Practice\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|##########| 2.55k/2.55k [00:00<?, ?B/s]


In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")

In [ ]:
type(score)

numpy.ndarray

In [ ]:
score.shape

(1167,)

In [ ]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [ ]:
len(score[score < 7])

332

In [ ]:
len(score)

1167

In [ ]:
len(score[score > 8])

609

In [ ]:
detractor_percent = len(score[score < 7]) / len(score) * 100

In [ ]:
promoter_percent = len(score[score > 8]) / len(score) * 100

In [ ]:
NPS = round((promoter_percent - detractor_percent),2)

In [ ]:
print(f"NPS is {NPS}")

NPS is 23.74
