<a href="https://colab.research.google.com/github/maharshi112/looking-forward/blob/master/Day_4_Numpy_4_Class_Prcatice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <code style="background:yellow;color:black">Copies of Data</code>

**As a data scientist, you will be working with millions of rows of data. So, numpy on top of being very fast, also has to be memory efficient, because if its not memory efficient your computer or system might run out of memory, and you wont be able to work with that dataset.**

So ultimately, storage space is a baseline requirement for numpy to be able to work with data because memory is continuosly either occupied or freed with each line of the program or with execution every of task. **Therefore, numpy internally has done a lot of optimizations so that it can optimize on storage / memory space.**

Lets suppose there is a bunch of data in excel. This data is for multiple cars. The cars data has 3 columns called Car model, Manufacturer and Date of launch. There are some entries i.e. rows in the data. <mark>REFER NOTES TO SEE DATA.</mark>

Lets suppose you only have to show data for tata, what would you do? Will you copy all the tata entries to another excel sheet or simply apply a filter to filter out tata entries? Obviously you will apply the filter on the manufacturer, which means that filter will show you the tata data, but the rest of the data will still be there.

**It means internally all the data is present but only filtered data is visible to you as the user. <mark>OR WE CAN ALSO SAY THAT BOTH THE DATAFRAMES OR BOTH THESE SOURCES OF DATA IS THE SAME, WE ARE JUST LOOKING AT DIFFERENT VIEWS OF THE DATA.</mark>**

Internally there is one single dataset, but we are just looking at different views of that same data. In one view, we are looking at all the manufacturers and in another view we are only looking at tata data.

Now, when it comes to numpy, we are doing as lot of operations on data. Some of those operations are permananet and some of those opearations are operations which can be either reversible or changed or are only done to present the data in a different format. These opearations do not change the structure or the value of the data but they just present the data differently.

**So NUMPY AUTOMATICALLY HAS DIVIDED ALL ITS OPERATIONS INTO THESE TWO CATEGORIES.**

**<mark>Category 1</mark>** are those opeartions which are permanent or important operations on data.

**<mark>Category 2</mark>** are operations which are just on the look of data or view of the data.

**AND IN BOTH THESE CASES NUMPY HANDLES MEMORY DIFFERENTLY. We will see this in action.**

In [ ]:
import numpy as np

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = a.reshape(2,2)

In [ ]:
b

array([[0, 1],
       [2, 3]])

If we look at a and b, both a and b are similar in data but different in the view of that data, which means they look and feel different and are presented differently but the data within them is the same.

**So in some such cases, what numpy does is it creates a <code style="background:yellow;color:black">SHALLOW COPY of data</code>.**

* **A shallow copy of an array means a new array that is a copy of the original array's data and shape but shares the same memory addresses as the original array. In other words, both of these arrays are sharing the same memory addresses.**
* **Changes made to the data within a shallow copy will also affect the original array, and vice versa.**
* To prove it, below we are changing a[0] to 100, obviously "a" gets modified and now has 100 as its 1st element, BUT B ALSO HAS THE SAME 100. IT ALSO CHANGED ITS 1ST ELEMENT.**  

**<mark>Numpy creates a shallow copy WHEN RESHAPING.</mark>**

**There is also a <code style="background:yellow;color:black">DEEP COPY.</code>**

* **A deep copy of an array is a completely independent copy of the original array, which means it has its own memory address. In other words, both of these arrays have different same memory addresses and are not sharing them.**
* **Changes made to a deep copy do not affect the original array, and vice versa.**

** We will learn a sure shot way to understand where will numpy create a shallow copy and where will it create a deep copy. **

So, what numpy has done internally, is that all the elements are shared between both the array a and b, so that when we modify one of the elements for one of the arrays, since the memory address was common and since the elements were shared between the two arrays, the b array also got affected. Here, numpy did not duplicate the data two times, what it did is actually created two pointers or references to that data, one reference was "a" and one reference was "b"; b and a were both looking at the data in different ways, but ultimately the data was exactly the same.

**To prove this or show this, numpy has a unique function called <mark>shares_memory()</mark>.**

* This is used to determine whether two arrays share the same memory block or addresses. This function returns a boolean value, indicating whether the two arrays share memory or not.
* The np.shares_memory() function takes two NumPy arrays as arguments and checks if they have overlapping memory or if they are views of the same data. If they share memory, the function returns True; otherwise, it returns False.

In [ ]:
a[0] = 100

In [ ]:
a

array([100,   1,   2,   3])

In [ ]:
b

array([[100,   1],
       [  2,   3]])

** This means that either "b" is a shallow copy of "a" or "a" is a shallow copy of "b" **

In [ ]:
np.shares_memory(a,b)

True

<mark>Now, when is numpy creating deep copy or how it works?</mark>

* Below we created a 1D np array "a".
* We also created another array "c" and make it a + 2.
* **Numpy considers addition, subtraction, multiplication these kind of operations to be more permanent in nature, because all the individual elements are updated or changed i.e. data is changed.**
* So if we create c from a, c has different data than a.
* Now if we check by "shares_memory()", we will see that a and c do not share memory.
* We can further prove this by changing first element of c to 100, and c array gets updated as we can see below. <mark>BUT ARRAY A IS NOT CHANGED AT ALL, ITS FIRST ELEMENT IS AS IT IS, IT HASNT CHANGED.</mark> Why because c was stored in an entirely memory location and a has been stored in an entirely different location and they do not share their memory addresses, and python can clear identify where a and c are located in memory locations.

**"C" IS A DEEP COPY OF "A". Why do we say that c is a copy of a although c is altogether a different array in terms of data? - BECAUSE C COPIED THE DATA FROM A AND THEN MODIFIED THE DATA BY ADDING 2 TO IT. IN OTHER WORDS, C TOOK A DEEP COPY OF A AND THEN ADDED 2 TO IT.**

**Numpy does all this decisions on whether to share memory or not internally on its own, but numpy has given us <mark>shares_memory()</mark> function to check the memory sharing between two np arrays.**

** Actually there are so many cases that in some memory is shared and in some memory isnt shared, and so remembering all those cases becomes difficult, so we have this function to check the same. **

In [ ]:
a = np.arange(4)

In [ ]:
c = a + 2

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
c

array([2, 3, 4, 5])

In [ ]:
np.shares_memory(a,c)

False

In [ ]:
c[0] = 100

In [ ]:
c

array([100,   3,   4,   5])

In [ ]:
a

array([0, 1, 2, 3])

** Now here in this case below, even though "a" and "b" both hold the same value or data, numpy doesvnot share memory addresses of these arrays, and it created a deep copy because it figured that a multiplication operation requires a deep copy. **  

In [ ]:
a = np.array([0,0,0,0])

In [ ]:
a

array([0, 0, 0, 0])

In [ ]:
b = a * 2

In [ ]:
a, b

(array([0, 0, 0, 0]), array([0, 0, 0, 0]))

In [ ]:
np.shares_memory(a,b)

False

* Here, in this case below, "a" and "b" have different data, they are not the same exact lists.
* But in this case, numpy allows sharing memory addresses of these two arrays.
* Lets look at it like the excel example previously.
* We can see "b" as a filter that has been applied on "a" or that "b" is a subset of "a".
* So all the data in "b" is still present inside of "a", which means if we modify the data in "a", data in "b" will be modified too because "b" is a subset of "a".
* We change the 1st element in "b" to 1000 and we check "a" is also updated.
* <mark>REFER NOTES VERY WELL EXPLAINED WITH VISUALIZATION.</mark>
* So, here we see that 2 different np arrays dont necessarily share data but they can share memory addresses because one can be a subset of the other.

Deep copy of one array wrt another array means both the arrays are stored at different memory locations in memory.

<mark>So, the cases are very varied apart. There can be cases where the data or values is different but a shallow copy is created and conversely there can be cases where the values can be same but the copy created is a deep copy.</mark>

**NUMPY DECIDES INTERNALLY AUTOMATICALLY WHICH COPY TO CREATE OR WHICH FORMAT OR RULE TO FOLLOW, which is the reason numpy has given us this shares_memory() function.**

** You can try or explore further and see whichc cases create a deep copy and which creates a shallow one. See what copies different kind of operations like arithmetic, logical, masking, indexing, slicing etc create. **

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
b[0] = 1000

In [ ]:
a

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
0 % 1

0

** This is another example to see if a shallow or deep copy is created, and we see a deep copy is created. **

In [ ]:
a = np.arange(6)

b = a[a % 1 == 0]

b[0] = 10

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
b

array([10,  1,  2,  3,  4,  5])

In [ ]:
np.shares_memory(a, b)

False

So, up and untill this point of time in disussion, we can to understand the following:

* **<mark>Shallow Copy is created in these cases - Reshaping, Slicing....(and the list goes on which you can explore)</mark>**
* **<mark>Deep Copy is created in these cases - Arithmetic Operations, Masking....(and the list goes on which you can explore)</mark>**

* Now, we know numpy creates shallow and deep copies of arrays and it handles memory management on its own.
* BUT WHAT IF WE WANT A SHALLOW OR DEEP COPY EXPLICITLY WITHOUT DOING ANY OPERATION ON THAT ARRAY, WITHOUT NUMPY DOING EVERYTHING ON ITS OWN, MEANS NUMPY DECIDING WHETHER IT WILL BE SHALLOW OR DEEP ON ITS OWN?

**<mark>There are 2 functions for this -- <code style="background:yellow;color:black">view()</code> creates shallow copy of array and <code style="background:yellow;color:black">copy()</code> creates deep copy of array.</mark>**

In the following examples we can see that.

In [ ]:
a = np.arange(10)

** Creates a shallow copy of "a". **

In [ ]:
a_shallow_copy = a.view()

In [ ]:
np.shares_memory(a, a_shallow_copy)

True

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_shallow_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a_shallow_copy[0] = 100

In [ ]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
a = np.arange(10)

** Creates a deep copy of "a". **

In [ ]:
a_deep_copy = a.copy()

In [ ]:
np.shares_memory(a, a_deep_copy)

False

**<mark>Why we are learning this shallow and deep copies or memeory management of numpy at a very higher level?</mark>**

* We should be aware of it because numpy functions that way or uses it for memeory optimization.
* If we are not aware of this, then we might feel that our data is misbehaving.
* We might not know why something else is changing while we are expecting something else.
* So, its very important to know how numpy is handling the memory side of things.

**We wont be using this concepts directly for data science, but this is sort of going to get applied unintentionally and we dont have control over it, which is why we should have a great understanding of it.**

We can dive deep between shallow nad deep copies, you can refer to these official documetations of numpy:

#### `.copy()` -- Returns copy of the array.

Documentation (`.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy

Documentation: (`np.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.copy.html

* When we are doing any operations on arrays, then numpy will decide automatically.
* But when we want ourself to create a copy of array, then control is with us, we can decide whether we want a shallow copy or deep copy using **.copy() or .view()**, otherwise during opeartions as mentioned earlier numpy automatically decides because numpy handles memory allocations automatically.
* Lets suppose we got a list that we need to sort.
* But in our use case, we need to maintain or dont want to destroy the original list, so we will create a copy of it in another list and then sort that copied list.
* Because lets suppose we need to present the original array and the sorted array both, so if we do an in-place sort on the original list, our unsorted original list is gone which we need to present somewhere.
* One way of doing this is like the code below -- np.sort(a) doesnt sort the original "a" but creates a copy of "a" in a_sorted list and then sorts it.
* Another way of doing it is to create a deep copy of "a" i.e. array "b".
* We cant do a shallow copy of "a" because then if we would sort "a" then "b" would also change. So we can see in code below that "b" is sorted but "a" is not sorted.

In [ ]:
a = np.array([10,15,25,5,20,0,30])

In [ ]:
a_sorted = np.sort(a)

In [ ]:
a

array([10, 15, 25,  5, 20,  0, 30])

In [ ]:
a_sorted

array([ 0,  5, 10, 15, 20, 25, 30])

In [ ]:
b = a.copy()

In [ ]:
b.sort()

In [ ]:
b

array([ 0,  5, 10, 15, 20, 25, 30])

In [ ]:
a

array([10, 15, 25,  5, 20,  0, 30])

**So, in any case where we have to maintain original data, where we cant loose the structure, order, authenticity of the original data but still we have to do multiple operations -- THERE WE WILL BE CREATING DEEP COPIES, i.e. copies of data which do not modify the original data.**

* We might do this frequently in data science.
* When we will be exploring data, we will have to do a lot of operations on data and some of these operations will not be successful.
* Whenever we will have unsuccessful operations, we will have to go back to the original data, but if we loose the original data, how will you do that?
* **So if we do not create a deep copy of the original data, we might have to reverse the operation we performed on data but every opeartion is not reversible. So for these reasons we have to maintain deep copies.**

## <code style="background:yellow;color:black">Splitting Data</code>

**Splitting the data means breaking the data into small pieces. For this, numpy has provided us a method called split().**

* Splitting the array using split() is somewhat similar and different as well compared to splitting strings.
* split() splits the array in similar fashion i.e. splitting something big into small small pieces but the way it works and the input it takes is different.
* Because it can split in 2 ways. Either it can split in an n amount of sections or it can split about an given amount of indexes. Both ways are explained below.

In [ ]:
a = np.arange(9)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### Splitting in n sections

** Format -- np.split(array, number_of_sections) **

In [ ]:
np.split(a, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

* Data is not divisible by number of sections, it will throw an error.
* SPLIT CAN ONLY AND ONLY WORK IF EVERY SINGLE SECTION WILL GET EQUIVALENT AMOUNT OF DATA. IF THE TOTAL NUMBER OF ELEMENTS IS NOT DIVISIBLE BY THE NUMBER OF SECTIONS YOU INTEND TO MAKE, THEN THE SPLIT() FUNCTION WILL NOT WORK.
* The example is shown below.

In [ ]:
b = np.arange(14)

In [ ]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
np.split(b, 3)

ValueError: array split does not result in an equal division

In [ ]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

#### Splitting on the basis of exact indexes

There is one more way when it comes to splitting np array. And that is by exact cutting points. SO lets supoose you got this entire array and you decided exactly where you want to split for example at index number 3 and at index number 5 and at index number 7. In the example below, we are splitting b at indexes 3,5,9.

In [ ]:
# np.split(array, [list_of_indexes])
# Np will create a split right before that index.

np.split(b, [3, 5, 9])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13])]

If the data is huge, and lets suppose its a 2D array, lets suppose you are dividing the data into two equal halves, lets suppose this is what I want, so first I will make sure that my data is divisible by 2. If my data is not divisible by 2, I will take out that last row nas store it in a seperate array, and then I will split the data into 2, append the last row back whichever way I want to append. I dont need to know the exact size of the data because I only need to provide the number of sections, and if I want to verify if my data can be divided into those many sections, I can simply check the length of the data- it will tell me how many rows of data I have.

In [ ]:
# Here we have 9 element 1D array, and we want to split the data into 4 sections- namely w,x,y,z

a = np.arange(10)

In [ ]:
z = a[-1]

In [ ]:
# Last section

z

9

In [ ]:
# Creating remaining 3 sections by not splitting the entire array a, but splitting from 0 to -1

w, x, y = np.split(a[0:-1], 3)

In [ ]:
w

array([0, 1, 2])

In [ ]:
x

array([3, 4, 5])

In [ ]:
y

array([6, 7, 8])

In [ ]:
a = np.arange(36).reshape(6,6)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

When it comes to 2D array, we can split data horizontally and we can split data vertically. To visualize more, REFER NOTES.

In [ ]:
# Splits the data on horizontal axis
# It works in the exact same way as split() i.e. in n number of sections or at specific indexes.
# Here we are doing splitting by n number of sections.


np.hsplit(a, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [ ]:
# Here we are doing splitting by specific indexes.

np.hsplit(a, [2,5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]])]

In [ ]:
# Note that there are no elemnets at 1000th index on horizontal axis, the index is out of range or out of bounds,
# so it will still split but will return an empty array at the end, and not throw an error.
# REFER NOTES FOR FOR CLARITY AND VIZUALIZATION.

np.hsplit(a, [2,5,1000])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]),
 array([], shape=(6, 0), dtype=int32)]

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
# Splits the data on vertical axis

np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [ ]:
np.vsplit(a, [1, 4])

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

## <code style="background:yellow;color:black">Stacking</code>

This is the opposite of splitting data, means joining data together, merging or stacking. So, we can stack data vertically and we can stack data horizontally. REFER NOTES HERE.

In [ ]:
data = np.arange(5)

In [ ]:
data

array([0, 1, 2, 3, 4])

In [ ]:
# This is same data stacked on top of one another in total 3 times.
# Note that vstack() function can have list as an argument or tuple as an argument too.
# So, np.vtack((data, data, data)) would work too, note that data is provided as a tuple as argument to vtack().

np.vstack([data, data, data])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
# NOTE THAT SHAPES OF ALL ARRAYS ARE SAME SO VSTACK WORKS.

a = np.arange(1,5)
b = np.arange(2,6)
c = np.arange(3,7)

In [ ]:
# This is different data stacked on top of one another in total 3 times.

np.vstack([a, b, c])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [ ]:
# NOTE THAT SHAPES OF ALL ARRAYS ARE DIFFERENT SO VSTACK DOES NOT WORK.

a = np.arange(1,5)
b = np.arange(2,4)
c = np.arange(3,10)

Whenever we are stacking, we have to make sure that the size or shape of the arrays are the same. There is a very legitimate reason for this.

Lets suppose you have data of stocks for 2015 to 2022. Now if you are adding data below it, the dimensions of the data have to mactch right. Otherwise the data would not make sense, the header would be something else the value would be something else or there will be a header and the value would be missing.

So, when the data that needs to be stacked or combined VERTICALLY, the data that is getting added should have the exact same number of columns. The number of rows can be different.

Note that in the example below "a" is a 1D array with 4 elements and "b" is a 2D array with shape of 4,4 and has 16 elements. Here, a and b has different number of rows but same number of columns. So, vstack() works.

When the data that needs to be stacked or combined HORIZONTALLY, the data that is getting added should have the exact same number of rows. The number of columns can be different.

These all concepts are explained below.

In [ ]:
np.vstack([a, b, c])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
a = np.arange(1,5)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b = np.arange(16).reshape(4,4)

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.vstack([b, a])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 1,  2,  3,  4]])

In [ ]:
a = np.arange(5).reshape(5, 1)

In [ ]:
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
b = np.arange(15).reshape(5, 3)

In [ ]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# Here a and b have same number of rows but different nnumber of columns. So hstack() works.

np.hstack([a, b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

## <code style="background:yellow;color:black">Concatenate</code>

Concatenate is one more way of doing stacking only, but it is like a combination function for both hstack and vstack, means it is a combined version of hstack and vstack.

For concatenate to work, there is a very very important constraint - both the arrays should have the same number of dimensions. Here in below example, a has 1D and b has 2D. So, concatenate will not work. So, there is a smart workaround. Simply convert 1D to 2D which is done below after the error. And that is by applying one more set of [] in a to make it a list inside a list i.e. 2D. Axis 0 means we are concatenating vertically.

In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a, b], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3], [4,5,6]])

In [ ]:
np.concatenate([a,b], axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

When it comes to concatenate there are following rules:
* Number of dimensions must be same
* Axis -
    * vstack -> axis = 0
    * hstack -> axis = 1

In [ ]:
a = np.arange(4).reshape(2,2)
b = np.arange(8).reshape(2,4)

In [ ]:
a

array([[0, 1],
       [2, 3]])

In [ ]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# a and b have same number of rows, so they can be concatenated horizontally. Note that axis = 1.

np.concatenate([b, a], axis = 1)

array([[0, 1, 2, 3, 0, 1],
       [4, 5, 6, 7, 2, 3]])

We dont have joins like sql in numpy or python. Why would we do sql joins in numpy? We have joins in sql so we dont need them in numpy. Means we do joins in sql and then w edont require joins operation in python.

There is a concept called DATA PIPELINE. Everyone of these tools, like sql, tableau, excel, python, numpy plays a seperate role in this data pipeline.

As a data analyst, its not that you will either use sql or you will use tableau or you will use python. YOU WILL ACTUALLY USE ALL OF THESE TOOLS.

SQL WILL BE FOR FETCHING DATA, PYTHON WILL BE FOR WORKING ON DATA. Within python also there will be two options one is numpy and one is pandas. Numpy is like the brain behind pandas. And, pandas has been built on top of numpy to work beautifully with data. So everythin and anything that you feel is required directly for data, you will find it in pandas and not numpy. SO YOU USE USE BOTH NUMPY AND PANDAS TOGETHER.

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

In above example, a and b both are nested arrays or 2D arrays. Now in below code, we are providing axis = None. Numpy has a special feature via which it will just flatten the entire array. What soes flattening mean? It means REMOVING NESTING. Removing dimensions, converting everything to one single dimension. Concatenate has this special feature.

In [ ]:
np.concatenate([a, b], axis = None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.flatten([[[[1,2,3]],[2,3,4,5,5,6,6]]])

AttributeError: module 'numpy' has no attribute 'flatten'

In [ ]:
a = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [ ]:
a.flatten()

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])