<a href="https://colab.research.google.com/github/maharshi112/looking-forward/blob/master/Day_3_Numpy_3_Class_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#### <mark>Refreshing old concept</mark>

**Quiz**

arr = np.arange(12) <br>
arr = arr.reshape(-1,4)

What will the shape of array ?

1. (-1, 4)
2. (12,)
3. (3, 4)
4. (1, 12)

In [ ]:
arr = np.arange(12)

In [ ]:
arr = arr.reshape(-1,4)

In [ ]:
arr.shape

(3, 4)

### <code style="background:yellow;color:black">Sort Method</code>

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

"b" stores the sorted version of "a", and sorting is in increasing order by default. **<mark>Original array "a" will remain unchanged</mark>,** because a sorted version of "a" is copied in "b" and "a" itself remains as it is. **<mark>This is called creating a COPY.</mark>**

In [ ]:
b = np.sort(a)

In [ ]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a)

[4 7 0 3 8 2 5 1 6 9]


In [ ]:
d = a

In [ ]:
d

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

**<mark>This is called IN-PLACE SORTING.</mark>** This does not create and return a sorted copy of the original np array, but it sorts the original np array itself, in this case "d".

This is directly applying sort() function to the original array. **<mark>This is the difference between np.sort(a) and a.sort()</mark>,** that when you provide np.sort(a) it will sort and return a copy of array "a", whereas a.sort() will sort the original array "a" itself, no copy will be created.

In [ ]:
d.sort()

In [ ]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### <code style="background:yellow;color:black">Argsort() Method</code>

<mark>sort() returns the sorted array and **argsort() returns the indexes of the array if it was sorted.</mark>**

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

** We get a np array which is telling us the INDEXES of the original array if they were in sorted order. <mark>Refer notes to visualize.</mark> **

In [ ]:
a.argsort()

array([2, 7, 5, 3, 0, 6, 8, 1, 4, 9], dtype=int64)

In [ ]:
b = np.array([5,7,3,1,10])

In [ ]:
b.argsort()

array([3, 2, 0, 1, 4], dtype=int64)

### <code style="background:yellow;color:black">ones() and zeros()</code>

**These methods will create an array of all 1's and all 0's.**

Below code will create a np array of 1s and how many 1s will be there is provided as a parameter. All of them will be floating point numbers. Here in the example below an array of 5 number of 1s will be created. If we would have provided 7 as a parameter, 7 number of 1s would have been created.

In [ ]:
a = np.ones(5)

In [ ]:
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.zeros(5)

In [ ]:
b

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### <code style="background:yellow;color:black">eye()</code>

**This method will create an identity matrix.**

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### <code style="background:yellow;color:black">Ufunc Sorting</code>

**In NumPy, a ufunc (universal function) is a function that operates element-wise on ndarray objects. NumPy provides a variety of ufuncs to perform operations such as arithmetic, trigonometric, and logical operations on arrays efficiently. Sorting in NumPy can be accomplished using ufuncs like numpy.sort() and numpy.argsort().**

**<mark>QUIZ-</mark>**

a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]]) <br>
b = np.sort(a)

What'll be value of b?

1. Error
2. [[  0,   3,   4],
    [ 12,  23,  43],
    [ 69,  89, 420]]

3. [[  4,  23,  43],
    [  3,  12,  89],
    [  0,  69, 420]]

4. [[  0,  12,  43],
    [  3,  23,  89],
    [  4,  69, 420]]


In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

In [ ]:
b = np.sort(a)

<mark>Here in 2D array, sorting is performed by last axis.</mark>

In this case, the last axis is AXIS 1, so it will perform sorting on axis 1. Axis 1 is row wise. So, it will perform sorting row wise. Sorted version of 1st row is 4 23 43, sorted version of 2nd row is 3 12 89 ans so on.

So, when we implement np.sort(a) where "a" is a 2D array, it will perform sorting on the basis on last axis.

In [ ]:
print(b)

[[  4  23  43]
 [  3  12  89]
 [  0  69 420]]


### <code style="background:yellow;color:black">Element wise operations</code>

<mark>Element wise multiplication of 1D arrays-</mark> It will be performed element wise, means 1st element of array 1 will be multiplied with 1st element of array 2 and so on, and the resulting array is returned, which in our case will be floating point numbers because one of the array is floating point.

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
b = np.arange(5)

In [ ]:
b

array([0, 1, 2, 3, 4])

In [ ]:
a * b

array([ 0,  1,  4,  9, 16])

In [ ]:
a = np.arange(1,13).reshape(3,4)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.arange(2,14).reshape(3,4)

In [ ]:
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

<mark>Element wise multiplication of 2D arrays-</mark> It will be performed element wise, means 1st element of 2D array 1 will be multiplied with 1st element of 2D array 2, 2nd element of 2D array 1 will be multiplied with 2nd element of 2D array 2 and so on, and the resulting 2D array is returned.

In [ ]:
a * b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

### <code style="background:yellow;color:black">Matrix Multiplication</code>

Matrix multiplication is same as we studied in school about how matrixes are multiplied i.e. matrix multiplication. This is however, different from element wise multiplication of arrays, which is seen above, and the only operator used for element wise multiplication is " <b>*</b> ".

**There is one important rule of matrix multiplication- that number of columns of 1st matrix should be of same as number of rows of 2nd matrix.**

**Second important rule is about the size of the resultant matrix. The number of rows of resultant matrix will be equal to number of rows of matrix 1 and columns of resultant matrix will be equal to number of columns of matrix 2.**

For example, Let M1 be a 2 X 3 matrix, M2 be a 3 X 5 matrix. What will be the shape of the resultant matrix? - 2 X 5. Let M1 be a 2 X 4 matrix, M2 be a 2 X 4 matrix. Matrix multiplication - Not possible.

<mark>There are 3 ways of matrix multiplication in numpy:</mark>

1. np.dot
2. @ operator
3. np.matmul

Among these np.matmul is most widely used.

In [ ]:
a = np.arange(1, 13).reshape(3,4)

In [ ]:
b = np.arange(2,14).reshape(4,3)

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


Can we do matrix multiplication of these two matrices? YES because number of rows of 1st matrix is equal to the number of cols of the 2nd matrix. And that can be confirmed by checking the shape of the two matrices.

What will be the shape of the resultant matrix? - 3 X 3

In [ ]:
a.shape

(3, 4)

In [ ]:
b.shape

(4, 3)

In [ ]:
np.dot(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
a @ b

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
np.matmul(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

### Quiz

What will be the shape of the output?

A = np.arange(10).reshape(5,2) <br>
B = np.arange(2).reshape(2,1) <br>
print(np.dot(A,B))

1. Error

2. (5,2)

3. (5,)

4. (5,1)

In [ ]:
A = np.arange(10).reshape(5,2)

In [ ]:
print(A)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
B = np.arange(2).reshape(2,1)

In [ ]:
print(B)

[[0]
 [1]]


In [ ]:
C = np.dot(A,B)

** The output is also called column vector. **

In [ ]:
print(C)

[[1]
 [3]
 [5]
 [7]
 [9]]


In [ ]:
C.shape

(5, 1)

<mark>Whats is the difference between 5,1 and 5, ?</mark>

5,1 is a 2D matrix of size 5 X 1, 5 rows and 1 column. Whereas, 5, is a 1D np array having 5 elements, thats it, there is no concept of rows and cols in 1D array.

In [ ]:
d = np.arange(5)

In [ ]:
d.shape

(5,)

In [ ]:
len(d)

5

### <code style="background:yellow;color:black">Vectorization</code>

**Vectorization is a fundamental concept in NumPy and other array computing libraries. It refers to the process of applying operations or functions to entire arrays or large sections of arrays at once, <mark>without the need for explicit Python for-loops.</mark>**

**Vectorization offers several advantages:**

* <u>Improved Performance:</u> Vectorized operations can be significantly faster than equivalent operations implemented using Python for-loops. This is because it can take advantage of hardware-level optimizations and parallelism which refers to taking advantage of multicore processors and parallel execution.

* <u>Simplified Code:</u> Vectorized code is often more concise and easier to read than equivalent code with explicit loops. This leads to more maintainable and understandable code.

In [ ]:
a = np.arange(1,13)

In [ ]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In terminology,

1. 1d np array is called vector
2. 2d np array is called matrix
3. 3d onwards is called tensors

** Below is element wise operation of multiplication. **

In [ ]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

** We can also create a function to apply some operation to all the elements of an array. **

In [ ]:
def solve(x):

    if x % 2 == 0:  # If x is even
        x = x * 2

    else:
        x = x * 3

    return x

In [ ]:
solve(5)

15

In [ ]:
solve(6)

12

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Now, we want to apply the solve function to every element of np array "a".

<u>Approach 1</u> is to apply loop, select a[i] and select the solve function, call solve(a[i]) for i in range(n). But this is a slow operation. <mark>Loops are not that fast.</Mark>

<mark><u>Approach 2</u> is **numpy vectorization.</mark>** Vectorization will do the same thing but in a very fast way. Vectorization effectively allows us to apply element-wise to a NumPy array. How to do that?

<mark>We have to create a **vectorized version** of the solve function. </mark>

For this, we define a new function called **<code style="background:yellow;color:black">vectorize()</code>** as shown below.

By this function, we vectorize the solve function. vectorize() function is a way to create a vectorized function from a non-vectorized (scalar) function.  So, essentially we are saying that I have created a function called solve, now create a vectorized form of that function and store it in a new function called aj_func.

In [ ]:
aj_func = np.vectorize(solve)

** This will not work because saolve func is not designed to have a np array as argument. **

In [ ]:
solve(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

** We can pass our np array "a" to the new vectorized aj_func and it works as expected. **

In [ ]:
aj_func(a)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**<code style="background:yellow;color:black">Use cases of vectorization:</code>**

1. **<u>We can apply vectorizaton on any python pre defined or in-built function:</u>** Here, we are vectorizing in-built log function of the math module of python. And then we are passing the entire np array "a" to that newly defined vectorized form of log function, to get log of all the elements of "a". Basically vectorization supports element-wise operations on arrays, where the same operation is applied to each element in an array.

2. **<u>Data Manipulation:</u>** Vectorization simplifies data manipulation tasks. You can easily perform tasks like filtering, transformation, or combining arrays without writing explicit loops.

In [ ]:
import math

In [ ]:
vectorized_log = np.vectorize(math.log)

In [ ]:
vectorized_log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [ ]:
b = np.arange(1,10).reshape(3,3)

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Vecorization also works on a 2D array as well.**

** Here every element is passed to the solve func and solve func does its work as required on every element individually. **

In [ ]:
aj_func(b)

array([[ 3,  4,  9],
       [ 8, 15, 12],
       [21, 16, 27]])

### <code style="background:yellow;color:black">Broadcasting</code>

**NumPy broadcasting is a powerful feature that allows NumPy to perform operations on arrays of different shapes, making it possible to combine and manipulate arrays that would otherwise have incompatible shapes.** Broadcasting is particularly useful when you want to perform element-wise operations on arrays of different shapes without having to explicitly reshape or tile the arrays to match.

**The key idea behind broadcasting is that when performing element-wise operations between two arrays, NumPy compares their shapes element-wise, from right to left. It starts by comparing the trailing dimensions (those with size 1 or that are missing) and then extends to the higher dimensions.**

In the first row in the image below, we are adding 2 matrices of size 4,3 so its simple element wise addition. Thats 1st element of 1st matrix is added with 1st element of 2nd matrix, 2nd element of 1st matrix is added with 2nd element of 2nd matrix and so on. So thats clear, easy and straightforward, and this is the ideal scenario.

Now in 2nd row of the image, if we try to add these two matrices of different sizes, one of 4,3 and other of 1,3, logically it should give error, because we cant perform element wise operation on 2 different sizes. But in some specific conditions, that we will soon learn, **2ND MATRIX WILL AUTOMATICALLY REPLICATE ITSELF OR ENLARGE ITSELF TO FIT IN THE SIZE OF THE 1ST MATRIX, AND THEN ELEMENT WISE OPERATION WILL HAPPEN.** The faint image tells us exactly this.

In 3rd case, we have one column matrix and one row matrix, both are of different sizes, so again if we try to add these two logically it should give error because we cant perform element wise operation on 2 different sizes. So what actually will happen is **1ST MATRIX WILL REPLICATE ITSELF TO MATCH FOR THE NUMBER OF COLUMNS OF 2ND MATRIX AND 2ND MATRIX WILL REPLICATE ITSELF TO FIT IN IN FOR THE NUMBER OF ROWS OF THE 1ST MATRIX, AND THEN ELEMENT WISE OPERATION HAPPENED AND WE GOT THE RESULT.** The faint image tells us exactly this.

Replication is done automatically. **THIS IS CALLED BROADCASTING. AND IT NOT ONLY APPLIES AUTOMATICALLY IN CASE OF ADDITION BUT ALSO APPLIES IN CASE OF MULTIPLICATION.**

Now, to understand how and why this happened, we need to understand "tile" function.
* In tile func, we pass 2 arguments- one the array, in our case "a", and a tuple containing the information about how many times we want to replicate the array "a" horizontally and vertically, or how many instances of the array we want horizontally and vertically.
* In our case, we passed a tuple (3,1) - this means replicate the array "a" or we want to create instances of the array such that in total it becomes 3 times horizontally. And replicate the array or create instances of the array such that it becomes 1 time vertically. So, we get the array having 3 rows and 4 cols because originally the array had 1 row and 4 cols.
* Here not to confuse (3,1) with the size of the resultant array. Its how many times we want to replicate the array or how many instances of the array we want horizontally and vertically.
* Please note that in tile func, if we pass array itself as the first argument and run it again and again, everytime the resultant array will be replicated again and again so that the result will inrease in size. Thats why we dont pass array as the first argument in tile func, instead we pass arange() so that everytime array will be generated as new and even if we we run this tile func again and again resultant array will be same everytime, it wont grow.

In [ ]:
a = np.arange(0,40,10)

In [ ]:
a

array([ 0, 10, 20, 30])

In [ ]:
a = np.tile(a, (3,1))

In [ ]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
b = np.arange(0,3)

In [ ]:
b

array([0, 1, 2])

In [ ]:
b = np.tile(np.arange(0,3), (4,1))

In [ ]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Now, can we perform a + b? Element wise addition? - NO. Because shape of b is 4,3 and shape of a is 3,4. So, we can do transpose of a to get shape of a as 4,3. Now we can do a + b to get element wise addition.

In [ ]:
b.shape

(4, 3)

In [ ]:
a.shape

(3, 4)

In [ ]:
a = a.T

In [ ]:
a.shape

(4, 3)

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b = np.arange(0,3)

In [ ]:
a.shape, b.shape

((4, 3), (3,))

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b

array([0, 1, 2])

Now, what will happen if we do a + b? As we learnt earlier, replication of 2nd array i.e. "b" will happen and then element wise addition will happen automatically.

**There is a <mark>RULE</mark> according to which this replication happens.**

We will understand whether broadcasting will be performed between 2 given np arrays or not.
* Lets take 2 np arrays of size (4,3) and (3,).
* What is the dimension of both the arrays?
* 1st array is 2D and 2nd array is 1D.
* So, first of all **MENTALLY** make 2nd array same dimension as 1st array, in our case we will make 2nd array as a 2D array.

How will we do it?

**WE WILL ALWAYS ADD THE MISSING DIMENSION AS "1" TO THE LEFT SIDE. <br>
HERE WE WILL VISUALIZE (3,) AS (1,3). <br>
<mark>SO OUR RULE SAYS - ALWAYS MAKE BOTH ARRAYS SAME DIMENSION BY PADDING THE ARRAY WITH "1" ON THE LEFT SIDE.</mark> <br>
REFER NOTES FOR MORE CLARITY. <br>
No matter how many dimensions to add, make it all 1s from the left.**

* Now we have two 2D arrays of size (4,3) and (1,3).
* Now from the right side go one by one and compare.
* REFER NOTES FOR MORE CLARITY.
* So here, we will compare right most dimension 3 of (4,3) to rightmost dimension 3 of (1,3).
* There are 2 things to check.
* First, whether they are same or not.
* Second, atleast one of them should be "1".
* If any of these two condition is satisfied in comparison, then that dimension is good to go.
* Similarly, compare each and every dimesnion and if every dimension is good to go, **<mark>THEN BROADCASTING WILL BE PERFORMED OTHERWISE NOT.</mark>**

Lets take another example.
* Lets take 2 np arrays as shown in last row of the image.
* Shape of 1st array is (4,1) its a 2D array.
* Shape of 2nd array is (3,) its a 1D array.
* REFER NOTES FOR MORE CLARITY ON THIS AND **<mark>DIFFERENCE BETWEEN 1D AND 2D ARRAYS.</mark>**
* Now lets see if broadcasting will be performed or not as per our rule.
* a is of shape (4,1) and b is of shape (3,).
* So we imagine b as (1,3) as explained in above example.
* Now check and compare rightmost dimesnions of both arrays i.e 1 of a and 3 of b.
* We see it satisfies our condition of atleast one of them should be "1", so good to go.
* Similarly 2nd dimension is also compared and found good to go. So, <mark>BROADCASTING WILL BE DONE.</mark>  

**After performing broadcasting, the shape of the resultant array will be maximum of both the arrays's dimension.**

In above example it will be (4,3).

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a = np.arange(0,40,10).reshape(4,1)

In [ ]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
b = np.arange(0,3)

In [ ]:
b

array([0, 1, 2])

In [ ]:
a.shape, b.shape

((4, 1), (3,))

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Quiz

In [ ]:
a = np.arange(8).reshape(2,4)

In [ ]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
b = np.arange(16).reshape(4,4)

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

* Here lets compare shape of a is (2,4) with that of b (4,4).
* Rightmost dimension satisfies the condition that values should be same, so its good to go.
* But, next dimesnion i.e. 2 and 4 doesnt satisfy both the conditions, that is values should be same or atleast one of them should be "1", so its not good to go.
* Hence, <mark>OVERALL BROADCASTING WILL NOT OCCUR, and a + b will throw an error.</mark>

In [ ]:
a + b

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [ ]:
A = np.arange(1,10).reshape(3,3)

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B = np.array([-1, 0, 1])

In [ ]:
B

array([-1,  0,  1])

* Broadcasting will be done and two np arrays will be multiplied.
* Basically, -1,0,-1 is getting replicated horizontally to make it a total 3 times, and then element wise multiplication happens.

In [ ]:
A * B

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

### Quiz

A = np.arange(12).reshape(3, 4) <br>
B = np.array([1, 2, 3])

What'll be the output of A + B ?

A. [[0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]] <br>
B. Error <br>
C. [[1, 2, 3, 4],
    [6, 7, 8, 9],
    [11,12,13,14]]

In [ ]:
A = np.arange(12).reshape(3, 4)

B = np.array([1, 2, 3])

A + B

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

### Quiz

Given two arrays of shape

1. Array A of shape  (8, 1, 6, 1)
2. Array B of shape (7, 1, 5)

Is broadcasting possible in this case? If yes, what will be the shape of output ?

* Broadcasting not possible as dimensions don't match
* Broadcasting not possible as dimension value 6 and 5 doesn't match
* Broadcasting possible. Shape will be (8, 1, 6, 5)
* Broadcasting possible; Shape will be (8, 7, 6, 5)


<mark>Answer will be D. Refer notes.</mark>

#### Doubts

In [ ]:
a = np.array([[4,2],
             [1,5]])

In [ ]:
a

array([[4, 2],
       [1, 5]])

** Sort the 2D array wrt axis 0 in ascending order, that is column wise. Sorting in descending order is HOMEWORK. **

In [ ]:
np.sort(a, axis = 0)

array([[1, 2],
       [4, 5]])

** Sort the 2D array wrt axis 1 in ascending order, that is row wise. **

In [ ]:
np.sort(a, axis = 1)

array([[2, 4],
       [1, 5]])